[#ref]
= Reference

// SPDX-FileCopyrightText: 2023 Mark Rotteveel
// SPDX-License-Identifier: Apache-2.0

This chapter describes the various configuration options.
First it describes the commandline options, followed by the XML configuration file format.

[#ref-cmd]
== Commandline options

_ext-table-gen_ provides a number of commandline configuration options to configure its behaviour.
We discuss the options here grouped by functional area.

[#ref-cmd-general]
=== General options

[#ref-cmd-help]
==== Help (`-h`, `--help`)

The help option (`-h` or `--help`) displays the general usage summary of _ext-table-gen_ and then exits.
The general usage summary is also printed for command-line errors.

[#ref-cmd-version]
==== Version (`-V`, `--version`)

The version option (`-V` or `--version`) prints version information and then exits.

[#ref-cmd-csv]
=== CSV file configuration

[#ref-cmd-csv-file]
==== CSV file (`--csv-file`)

The CSV file option (`--csv-file=FILE`) specifies the path of the CSV file.
`FILE` is the absolute or relative path to the file.
Relative paths are resolved against the current working directory.
The file must be in {link-rfc4180}[RFC 4180^] format.

We recommend specifying absolute paths, as the configuration file will store the path as specified, which means that if a relative path is used, and the configuration file is then used from a different location, it may attempt to read a non-existent or wrong file.

This option can override the XML config of <<ref-xml-csvfile,`/extTableGenConfig/csvFile[@path]`>>.

[#ref-cmd-csv-charset]
==== CSV character set (`--csv-charset`)

The CSV character set option (`--csv-charset=CHARSET`) specifies the character set of the CSV file.
`CHARSET` is any valid Java character set name or alias.
The default is `UTF-8`.

This option can override the XML config of <<ref-xml-csvfile,`/extTableGenConfig/csvFile[@charset]`>> if explicitly specified.

[#ref-cmd-csv-header]
==== CSV header (`--[no-]csv-header`)

The CSV header boolean option (`--[no-]csv-header`) specifies if the first row of the CSV file is a header (`--csv-header`, the default), or data (`--no-csv-header`).
The default is `--csv-header`.

If the first row is a header, and the external table is derived, the values in the first row are used as column names.
If an existing external table configuration is used, the header row is skipped.

If the first row is not a header, and the external table is derived, columns are assigned a name in the form of `++COLUMN_++__idx__`, where _idx_ is the 1-based index of the column (first is `COLUMN_1`, second is `COLUMN_2`, etc.).

This option can override the XML config of <<ref-xml-csvfile,`/extTableGenConfig/csvFile[@headerRow]`>> if explicitly specified.

[#ref-cmd-output]
=== External table file configuration

[#ref-cmd-table-file]
==== Table file path (`--table-file`)

The table file path option (`--table-file=FILE`) specifies the path of the external table file.
`FILE` is the absolute or relative path to the file.
Relative paths are resolved against the current working directory.

We recommend specifying absolute paths, as the configuration file will store the path as specified, which means that if a relative path is used, and the configuration file is then used from a different location, it may attempt to write to the wrong location or file.

This option can override the XML config of <<ref-xml-tablefile,`/extTableGenConfig/externalTable/tableFile[@path]`>>.
If specified, the XML config of `/extTableGenConfig/externalTable/tableFile[@overwrite]` is ignored, and defaults to `false` if <<ref-cmd-overwrite-table-file,`--overwrite-table-file`>> is not specified.

[#ref-cmd-overwrite-table-file]
==== Overwrite table file (`--[no-]overwrite-table-file`)

The overwrite table file boolean option (`--[no-]overwrite-table-file`) specifies if an existing external table file can be overwritten (`--overwrite-table-file`) or not overwritten (`--no-overwrite-table-file`, the default).
The default is `--no-overwrite-table-file`.

This option can only be specified if <<ref-cmd-table-file,`--table-file`>> is specified.
In other words, it does not override the XML config.

[CAUTION]
====
We only allow this override if also specifying the external table file, so you're aware what file you're going to overwrite.
====

[#ref-cmd-tbl-derive]
=== Table configuration and derivation

Table derivation options configure how _ext-table-gen_ derives the external table definition.

Apart from <<ref-cmd-table-name,`--table-name`>> and <<ref-cmd-byte-order,`--byte-order`>>, these options only have effect when a new external table definitions is generated (see also <<ref-cmd-table-derivation-mode>>).

[#ref-cmd-table-name]
==== Table name (`--table-name`)

The table name option (`--table-name=NAME`) specifies the name of the external table.
`NAME` is the table name.
The value will be converted to a quoted identifier.
When no name is specified through `--table-name` or the XML file, the table name `DEFAULT_EXTERNAL_TABLE_NAME` is used.

This option can override the XML config of <<ref-xml-externaltable,`/extTableGenConfig/externalTable[@name]`>> if explicitly specified.

[#ref-cmd-byte-order]
==== Byte order (`--byte-order`)

The byte order option (`--byte-order=ORDER`) specifies the byte order of the external table.
`ORDER` can have value:

[horizontal]
`BIG_ENDIAN`::
big-endian
`LITTLE_ENDIAN`::
little-endian
`AUTO`::
automatically select based on the byte order of the runtime platform

The default is the effective value of `AUTO` (that is, either `BIG_ENDIAN` or `LITTLE_ENDIAN`).
Explicitly specifying `AUTO` will store  `AUTO` in the configuration file.

This option can override the XML config of <<ref-xml-externaltable,`/extTableGenConfig/externalTable[@byteOrder]`>> if explicitly specified.

[#ref-cmd-column-encoding]
==== Column encoding (`--column-encoding`)

The column encoding option (`--column-encoding=ENCODING`) specifies the column encoding to use for all columns when deriving a table.
`ENCODING` is the Firebird name of a supported Firebird character set.
Default value is `ISO8859_1`.

This option can override the XML config of <<ref-xml-tablederivation,`/extTableGenConfig/tableDerivation[@columnEncoding]`>> if explicitly specified.
It does not override the column encoding of existing columns (unless you use an explicit <<ref-cmd-table-derivation-mode>>).

[#ref-unsupported-encoding]
===== Unsupported character sets

Not all Firebird character sets are supported.
`OCTETS` and `NONE` are not supported, as we need to know which character set to use to encode string data when writing the external table file, so we require that a "`real`" character set is specified as the column encoding.
The character set `UNICODE_FSS` is not supported, as we can't support this variant of UTF-8 with the standard Java character sets.
Other multibyte character sets (`SJIS_0208`, `EUCJ_0208`, `KSC_5601`, `BIG_5`, `GB_2312`, `GBK`, `CP943C`, `GB18030`) are not supported as we're not sure how to handle padding for these character sets (support may be added in the future after we've experimented with this).
Character sets which have no equivalent Java character set are also not supported (e.g. `NEXT`, `CYRL`).

[#ref-cmd-end-column]
==== End column type (`--end-column`)

The end column type option (`--end-column=TYPE`) specifies if an extra column is added with a linebreak, and if so, what linebreak.
`TYPE` can have value:

[horizontal]
`LF`::
linefeed, a.k.a. LF, \n, or 0x0a
`CRLF`::
carriage return + linefeed, a.k.a CR/LF, \r\n, or 0x0d0a
`NONE`::
no end column

The default is `LF`.

An end column is not necessary, but can improve the "`human readability`" of the external table file by starting each row on a new line.
If this is no concern for you, use `--end-column=NONE` to reduce file size and overhead of writing and reading this column.

This option can override the XML config of <<ref-xml-tablederivation,`/extTableGenConfig/tableDerivation[@endColumnType]`>> if explicitly specified.
It does not override the current end-column of `/extTableGenConfig/extTable/columns/endColumn` (unless you use an explicit <<ref-cmd-table-derivation-mode>>).

[#ref-cmd-table-derivation-mode]
==== Table derivation mode (`--table-derivation-mode`)

The table derivation mode option (`--table-derivation-mode=MODE`) specifies when an external table definition should be derived from a CSV file.
`MODE` can have value:

[horizontal]
`INCOMPLETE`::
Only derive the external table when the current configuration is incomplete.
`ALWAYS`::
Always derive the external table, even if the current configuration defines a valid external table.
`NEVER`::
Never derive the external table, always use the current configuration.
Fails if the current configuration is incomplete or invalid.
+
Specifying `NEVER` on the commandline is technically possible, but rarely makes sense, except maybe to make the behaviour explicit.

The formal default is `INCOMPLETE`, but this is only applied when <<ref-cmd-config-in, `--config-in`>> is not specified, and without an existing configuration, `INCOMPLETE` and `ALWAYS` behave the same.

When <<ref-cmd-config-in,`--config-in`>> is specified, the default is `NEVER`.
This default was chosen to avoid accidentally deriving a new table configuration and creating an external table file which does not match the existing external table used by Firebird server (e.g. because the config file was modified incorrectly, or because _ext-table-gen_ incorrectly or due to implementation changes suddenly considers the configuration as incomplete or invalid).
The assumption is that if you have an existing configuration file, it is complete and correct.
If that is not the case, or if you want to derive the external table definition anew, you must explicitly declare this with `--table-derivation-mode`.

[#ref-cmd-config]
=== Configuration file management

[#ref-cmd-config-in]
==== Configuration input (`--config-in`)

The configuration input (`--config-in=FILE`) specifies the path of the configuration file to read.
`FILE` is the absolute or relative path to the file to read.

The configuration input is used as the initial configuration, and can be modified by the other commandline options.
If `--config-in` is not specified, the default values are applied in the absence of a commandline option.

[#ref-cmd-config-out]
==== Configuration output (`--config-out`)

The configuration output (`--config-out=FILE`) specifies the path of the configuration XML file to write.
`FILE` is the absolute or relative path to the file to read.

If `--config-out` is not specified, no configuration file is written.
By default, an existing configuration file is not overwritten.
Specify <<ref-cmd-overwrite-config,`--overwrite-config`>> to overwrite an existing configuration file.

If the configuration file exists and <<ref-cmd-overwrite-config,`--overwrite-config`>> is not specified, this is reported on the standard error output.
The export of the CSV to an external table will proceed as normal.

When both <<ref-cmd-config-in,`--config-in`>> and `--config-out` are specified without other options (except <<ref-cmd-overwrite-config,`--overwrite-config`>>), generally a file with the same configuration will be written, except for:

. New configuration options introduced in _ext-table-gen_ after the configuration input was created
. The content of the informational element is always regenerated, so if it was outdated (e.g. see <<usage-config-regen>>), or _ext-table-gen_ changed how the DDL or other information is generated, it may change.

When both <<ref-cmd-config-in,`--config-in`>> and `--config-out` are specified with other options, the values of those options are reflected in the new configuration file.

Except for the table name (`/extTableGenConfig/externalTable[@name]`) and table file (`/extTableGenConfig/externalTable/tableFile`), the <<ref-xml-externaltable>> element will not change unless <<ref-cmd-table-derivation-mode,`--table-derivation-mode=ALWAYS`>> is specified, or the existing configuration is considered invalid or incomplete and `--table-derivation-mode=INCOMPLETE` is specified.

[#ref-cmd-overwrite-config]
==== Overwrite configuration (`--[no-]overwrite-config`)

The overwrite configuration boolean option (`--[no-]overwrite-config`) specifies whether the configuration output (<<ref-cmd-config-out,`--config-out`>>) can be overwritten if it exists (`--overwrite-config`) or not overwritten (`--no-overwrite-config`, the default).
The default is `--no-overwrite-config`.

This option can only be specified if <<ref-cmd-config-out,`--config-out`>> is specified.

The option `--no-overwrite-config` is technically unnecessary, but can be specified for explicitness (and exists for consistency with other boolean options).

[#ref-xml]
== XML configuration

The XML configuration file format uses an XSD to define its structure.
This XSD can be found in <<#xsd>>.
This section follows the structure of the XSD.

The root of the XML is `extTableGenConfig`.

.Attributes
None

.Elements
* <<ref-xml-externaltable>> -- required
* <<ref-xml-tablederivation>> -- optional
* <<ref-xml-csvfile>> -- optional
* <<ref-xml-informational>> -- optional

[#ref-xml-externaltable]
=== `externalTable`

The `externalTable` element defines the name, columns and table file of the external table.
The columns it contains are used by _ext-table-gen_ to validate the columns in the input CSV file (e.g. number of columns, length of column values), and format the output of the external table file, and generate the DDL of the table.

.Attributes
[horizontal]
`name`::
Name of the table (used for the DDL; required)
`byteOrder`::
Byte order of the table (optional)
Possible values:
+
--
[horizontal]
`BIG_ENDIAN`::
big-endian
`LITTLE_ENDIAN`::
little-endian
`AUTO`::
automatically select based on the byte order of the runtime platform
--
+
If the attribute is absent, `AUTO` is used.

.Elements
* <<ref-xml-columns>> -- required
* <<ref-xml-tablefile>> -- optional

[#ref-xml-columns]
==== `columns`

The element `columns` is a sequence of one or more <<ref-xml-column>> elements, defining the columns of the external table.

.Attributes
None

.Elements, in order
* <<ref-xml-column>> -- one or more
* <<ref-xml-endcolumn>> -- optional

[#ref-xml-column]
===== `column`

The `column` element defines a normal data column.

.Attributes
[horizontal]
`name`::
Name of the column (used for the DDL; required)

.Elements
* Element of type <<ref-xml-datatype,datatype>> -- required

[#ref-xml-datatype]
====== datatype

A datatype is a placeholder for an element corresponding to a specific Firebird data type.

.Attributes
None, though subtypes may define attributes

.Elements, in order
* <<ref-xml-converter>> -- optional

At this time, _ext-table-gen_ supports the following column data types:

* <<ref-xml-bigint>>
* <<ref-xml-char>>
* <<ref-xml-date>>
* <<ref-xml-decimal>>
* <<ref-xml-int128>>
* <<ref-xml-integer>>
* <<ref-xml-numeric>>
* <<ref-xml-smallint>>
* <<ref-xml-time>>
* <<ref-xml-timestamp>>

[float#ref-xml-bigint]
====== `bigint`

The `bigint` elements represents the Firebird datatype `BIGINT`.

.Attributes
None

.Elements
* <<ref-xml-converter>> -- optional

[float#ref-xml-char]
====== `char`

The `char` element represents the Firebird datatype `CHAR`.

.Attributes
[horizontal]
`length`::
Integer in the range [1, 32767] with length in Unicode codepoints (required). +
The XSD does not validate maximum length for multibyte character sets (e.g. for `encoding="UTF8"` the actual maximum length would be 8191, but this is not enforced).
`encoding`::
Encoding (character set) of the column, using Firebird character set names (required). +
The XSD uses an enum-type, `encoding`, with supported names.

.Elements
* <<ref-xml-converter>> -- optional

[float#ref-xml-date]
====== `date`

The `date` element represents the Firebird datatype `DATE`.
The Firebird `DATE` type only accepts values between 0001-01-1 and 9999-12-31.

The default conversion parses the string using the ISO 8601 calendar date format (pattern `yyyy-MM-dd`, or named pattern `ISO_LOCAL_DATE`).

.Attributes
None

.Elements
* <<ref-xml-converter>> -- optional

[float#ref-xml-decimal]
====== `decimal`

// NOTE: keep in-sync with ref-xml-numeric

The `decimal` element represents the Firebird datatype `DECIMAL`.

The default conversion parses the string using the rules described in the constructor https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/math/BigDecimal.html#%3Cinit%3E(java.lang.String)[`BigDecimal(String)`^].
Contrary to the `parseBigDecimal` converter, this converter can also parse strings in scientific notation.

.Attributes
[horizontal]
`precision`::
Integer in the range [1, 38] for the precision in decimal digits (required). +
Precision greater than 19 requires Firebird 4.0 and higher.
`scale`::
Integer in the range [0, _scale_] for the scale in decimal digits (required). +
The XSD does not enforce that _scale_ must be less than or equal to _precision_.
`roundingMode`::
Rounding mode applied when reducing the scale of a parsed number with more digits after the decimal point than allowed by _scale_ (optional, defaults to `HALF_UP`). +
The XSD uses an enum-type, `roundingMode`, with supported names. +
Possible values are:
+
--
[horizontal]
`CEILING`:::
Round towards positive infinity.
`DOWN`:::
Round towards zero.
`FLOOR`:::
Round towards negative infinity.
`HALF_DOWN`:::
Round towards "`nearest neighbor`" unless both neighbors are equidistant, in which case round down.
`HALF_EVEN`:::
Round towards the "`nearest neighbor`" unless both neighbors are equidistant, in which case, round towards the even neighbor.
`HALF_UP`:::
(default) Round towards "`nearest neighbor`" unless both neighbors are equidistant, in which case round up.
`UNNECESSARY`:::
Asserts that the requested operation has an exact result, hence no rounding is necessary. +
Using this rounding mode will reject values with more non-zero digits after the decimal point than _scale_.
`UP`:::
Round away from zero.
--

The _precision_ is used only to determine the backing datatype, and is not used to enforce length limits.
Just like in Firebird itself, the allowed range of values is determined by the backing datatype.
For `DECIMAL`, that means:

[horizontal]
`1 {lt}= precision {lt}= 9`::
`INTEGER`, unscaled range [-2147483648, 2147483647]
`10 {lt}= precision {lt}= 18`::
`BIGINT`, unscaled range [-9223372036854775808, 9223372036854775807]
`19 {lt}= precision {lt}= 38`::
`INT128`, unscaled range [-170141183460469231731687303715884105728, 170141183460469231731687303715884105727]

.Elements
* <<ref-xml-converter>> -- optional

[float#ref-xml-int128]
====== `int128`

The `int128` element represents the Firebird datatype `INT128`.

.Attributes
None

.Elements
* <<ref-xml-converter>> -- optional

[float#ref-xml-integer]
====== `integer`

The `integer` element represents the Firebird datatype `INTEGER`.

.Attributes
None

.Elements
* <<ref-xml-converter>> -- optional

[float#ref-xml-numeric]
====== `numeric`

// NOTE: keep in-sync with ref-xml-decimal

The `numeric` element represents the Firebird datatype `NUMERIC`.

The default conversion parses the string using the rules described in the constructor https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/math/BigDecimal.html#%3Cinit%3E(java.lang.String)[`BigDecimal(String)`^].
Contrary to the `parseBigDecimal` converter, this converter can also parse strings in scientific notation.

.Attributes
[horizontal]
`precision`::
Integer in the range [1, 38] for the precision in decimal digits (required). +
Precision greater than 19 requires Firebird 4.0 and higher.
`scale`::
Integer in the range [0, _scale_] for the scale in decimal digits (required). +
The XSD does not enforce that _scale_ must be less than or equal to _precision_.
`roundingMode`::
Rounding mode applied when reducing the scale of a parsed number with more digits after the decimal point than allowed by _scale_ (optional, defaults to `HALF_UP`). +
The XSD uses an enum-type, `roundingMode`, with supported names. +
Possible values are:
+
--
[horizontal]
`CEILING`:::
Round towards positive infinity.
`DOWN`:::
Round towards zero.
`FLOOR`:::
Round towards negative infinity.
`HALF_DOWN`:::
Round towards "`nearest neighbor`" unless both neighbors are equidistant, in which case round down.
`HALF_EVEN`:::
Round towards the "`nearest neighbor`" unless both neighbors are equidistant, in which case, round towards the even neighbor.
`HALF_UP`:::
(default) Round towards "`nearest neighbor`" unless both neighbors are equidistant, in which case round up.
`UNNECESSARY`:::
Asserts that the requested operation has an exact result, hence no rounding is necessary. +
Using this rounding mode will reject values with more non-zero digits after the decimal point than _scale_.
`UP`:::
Round away from zero.
--

The _precision_ is used only to determine the backing datatype, and is not used to enforce length limits.
Just like in Firebird itself, the allowed range of values is determined by the backing datatype.
For `NUMERIC`, that means:

[horizontal]
`1 {lt}= precision {lt}= 4`::
`SMALLINT`, unscaled range [-32768, 32767]
`5 {lt}= precision {lt}= 9`::
`INTEGER`, unscaled range [-2147483648, 2147483647]
`10 {lt}= precision {lt}= 18`::
`BIGINT`, unscaled range [-9223372036854775808, 9223372036854775807]
`19 {lt}= precision {lt}= 38`::
`INT128`, unscaled range [-170141183460469231731687303715884105728, 170141183460469231731687303715884105727]

.Elements
* <<ref-xml-converter>> -- optional

[float#ref-xml-smallint]
====== `smallint`

The `smallint` element represents the Firebird datatype `SMALLINT`.

.Attributes
None

.Elements
* <<ref-xml-converter>> -- optional

[float#ref-xml-time]
====== `time`

The `time` elements represents the Firebird datatype `TIME [WITHOUT TIME ZONE]`.
The Firebird `TIME` type only accepts values between 00:00:00.0000 and 23:59:59.9999.

.Attributes
None

.Elements
* <<ref-xml-converter>> -- optional

[float#ref-xml-timestamp]
====== `timestamp`

The `timestamp` elements represents the Firebird datatype `TIMESTAMP [WITHOUT TIME ZONE]`.
See also the limitations of <<ref-xml-date>> and <<ref-xml-time>>.

For additional flexibility, the time part is not required.
For example if you use a `parseDatetime` with a pattern which only provides date information, but doesn't provide time information (e.g. `yyyy-MM-dd`), it will save the date with time set to 00:00:00.0000.

.Attributes
None

.Elements
* <<ref-xml-converter>> -- optional

[#ref-xml-converter]
===== `converter`

The `converter` element -- if present -- defines a conversion from the CSV string value to a Firebird data type value.
If absent, a default conversion will be applied, specific to the column data type.

.Attributes
None

.Elements
* One of the _converter steps_ listed below -- required

.Available converter steps
* <<ref-xml-parsebigdecimal>>
* <<ref-xml-parsedatetime>>
* <<ref-xml-parseintegralnumber>>

[NOTE]
====
The name _converter step_ may seem to imply that a converter can consist of multiple steps chained together.
That is currently not supported, but it is something that may be introduced in a future version.

In the actual program code, a _converter step_ is also called a _converter_, but in this manual we wanted to prevent overloading the term as it already refers to the `converter` element.
====

[float#ref-xml-parsebigdecimal]
====== `parseBigDecimal`

Parses a string using the Java `NumberFormat` instance for the specified locale to a `BigDecimal`.

This converter step is only valid in <<ref-xml-decimal>> and <<ref-xml-numeric>>.
Contrary to the default converter of `numeric` and `decimal`, this converter does not parse strings in scientific notation.

.Attributes
[horizontal]
`locale`::
Locale as a https://www.ietf.org/rfc/bcp/bcp47.txt[BCP 47^] language tag (required)

.Elements
None

[float#ref-xml-parsedatetime]
====== `parseDatetime`

Parses a string using the specified pattern and locale to a datetime value.

This converter step is only valid in <<ref-xml-date>>, <<ref-xml-time>>, and <<ref-xml-timestamp>>.

.Attributes
[horizontal]
`pattern`::
Datetime pattern, or one of the pre-defined formatter names (required)
+
The pattern format uses the syntax described in https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/time/format/DateTimeFormatter.html[`java.time.format.DateTimeFormatter`^].
The pre-defined formatter names are the constants listed under _Field Summary_ in https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/time/format/DateTimeFormatter.html#field-summary[`DateTimeFormatter`^].
+
In addition, the following custom pre-defined formatter names are available:
+
--
* `SQL_TIMESTAMP` -- basically the same as `ISO_LOCAL_DATE_TIME`, but uses a space as the separator instead of `T`.
--

`locale`::
Locale as a https://www.ietf.org/rfc/bcp/bcp47.txt[BCP 47^] language tag (optional)
+
Generally only relevant to parse datetime strings with localized names for months and days.

.Elements
None

[float#ref-xml-parseintegralnumber]
====== `parseIntegralNumber`

Parses a string using a specified radix to an integral number of the type of the enclosing datatype.

This converter step is only valid in <<ref-xml-bigint>>, <<ref-xml-integer>>, <<ref-xml-int128>>, and <<ref-xml-smallint>>.

.Attributes
[horizontal]
`radix`::
Radix for parsing a string to an integral number.
Default `10`, range [2, 36].

.Elements
None

[#ref-xml-endcolumn]
==== `endColumn`

The `endColumn` elements represents an extra column which is added to the external table to introduce a linebreak after each row in the external table file.
This linebreak is primarily intended to make the file more "`human-readable`", and is not needed for Firebird itself.

.Attributes
[horizontal]
`type`::
Type of linebreak (required) +
Possible values:
+
--
[horizontal]
`LF`:::
Linefeed (\n or 0x0a)
`CRLF`:::
Carriage return and linefeed (\r\n or 0x0d0a)
--
+
There is no value equivalent to <<ref-cmd-end-column,`--end-column=NONE`>>.
Instead, that is represented by absence of the `endColumn` element.

.Elements
None

[#ref-xml-tablefile]
==== `tableFile`

The element `tableFile` specifies the external table file.

.Attributes
[horizontal]
`path`::
Path of the external table file (required). +
If a relative path, it is resolved against the current working directory of _ext-table-gen_.
It is recommended to use absolute paths.
`overwrite`::
Boolean specifying if _ext-table-gen_ is allowed to overwrite an existing file (optional; defaults to `false`)

.Elements
None

[#ref-xml-tablederivation]
=== `tableDerivation`

The element `tableDerivation` stores the configuration used to derive an external table.
This is only used when _ext-table-gen_ is used with <<ref-cmd-table-derivation-mode,`--table-derivation-mode=ALWAYS`>>, or `--table-derivation-mode=INCOMPLETE` and the current configuration is considered incomplete or invalid.

Be aware, it does not necessarily represent the configuration used to derive the current table described by <<#ref-xml-externaltable>>, but instead the last configuration stored using <<ref-cmd-config-out,`--config-out`>>.

.Attributes
[horizontal]
`columnEncoding`::
Encoding (character set) to apply to columns when deriving an external table (optional). +
The XSD uses an enum-type, `encoding`, with supported names.
`endColumnType`::
Type of linebreak (optional) +
Possible values:
+
--
[horizontal]
`LF`:::
Linefeed (\n or 0x0a)
`CRLF`:::
Carriage return and linefeed (\r\n or 0x0d0a)
`NONE`:::
No end column
--
+
Absence of the attribute implies `LF`.

.Elements
None

The commandline option <<ref-cmd-table-derivation-mode>> is intentionally not represented in the configuration file.
If a configuration file is specified (using <<ref-cmd-config-in,`--config-in`>>), _ext-table-gen_ defaults to `NEVER`, and needs to be explicitly overridden by the commandline to derive the external table.

[#ref-xml-csvfile]
=== `csvFile`

The element `csvFile` specifies the CSV file to use, and how to read it.

.Attributes
[horizontal]
`path`::
Path of the CSV file (required). +
If a relative path, it is resolved against the current working directory of _ext-table-gen_.
It is recommended to use absolute paths.
`charset`::
Character set of the CSV file (required). +
Expects a Java character set name or alias.
As available character sets depend on the JVM and its classpath, this is not restricted by the XSD.
`headerRow`::
Boolean specifying if the first row of the CSV file is a header row or a data row (optional; defaults to `true`)

.Elements
None

[#ref-xml-informational]
=== `informational`

The element `informational` contains data which is informational only, and does not represent configuration used by _ext-table-gen_.
Be aware that if the configuration file was changed outside _ext-table-gen_, the contents of `informational` may be out-of-sync.
See <<usage-config-regen>> on how to regenerate the config file.

.Attributes
None

.Elements
* <<ref-xml-ddl>> -- required

[#ref-xml-ddl]
==== `ddl`

The `ddl` element contains the Firebird https://www.firebirdsql.org/file/documentation/chunk/en/refdocs/fblangref40/fblangref40-ddl-table.html#fblangref40-ddl-tbl-create[`CREATE TABLE`^] statement derived from <<ref-xml-externaltable>>.

.Attributes
None

.Elements
None
