# SPDX-FileCopyrightText: Copyright 2026 Mark Rotteveel
# SPDX-License-Identifier: Apache-2.0
#
# Example of integration-test-local.properties that will work with the setup in podman-compose.yml.
#
test.db.host=localhost
test.db.port=13055
test.db.user=sysdba
test.db.password=masterkey
test.db.path.prefix=
test.db.path.local=./.test-db
test.db.ext-table-dir.prefix=
test.db.ext-table-dir.local=./.test-db