= Firebird External Table Generator: Release notes
Mark Rotteveel
{etg-version}
:doctype: book
:docinfo:
:sectanchors:
:forceinclude: true
:keywords: firebird, database, external table
:source-highlighter: prettify
:toc: left
:outlinelevels: 6:1
:icons: font
:sectnums:
:link-rfc4180: https://www.rfc-editor.org/rfc/rfc4180

// SPDX-FileCopyrightText: 2023 Mark Rotteveel
// SPDX-License-Identifier: Apache-2.0

Copyright 2023 Mark Rotteveel and all contributing authors under the https://www.apache.org/licenses/LICENSE-2.0[Apache 2.0 license^].

toc::[]

[#intro]
== Introduction

The "`Firebird External Table Generator`" or _ext-table-gen_ is a commandline tool to convert {link-rfc4180}[RFC 4180^] CSV files and CSV files with custom formats to https://www.firebirdsql.org/[Firebird^] external tables (a binary format for Firebird external table data).

External tables are a good way for bulk-loading data into Firebird.
Unfortunately, external tables use a fixed-width _binary_ formatfootnote:[The format is essentially the in-memory layout of rows which Firebird also uses internally], and not a (more) standard format like CSV.
It is not always easy to create an appropriate external table file, and this is where _ext-table-gen_ can be used.

At a high level, _ext-table-gen_ provides the following features:

* Derive a `CHAR`-based external table definition (i.e. a `CREATE TABLE` statement and a configuration for _ext-table-gen_) from a CSV file
* Transform a CSV file to an external table file (either based on the CSV file itself, or based on a configuration file)

By default, _ext-table-gen_ derives tables with only `CHAR` columns.
This makes the generated file essentially a fixed-width text format.
However, you can modify the configuration file to make _ext-table-gen_ generate columns of different types, in which case the file becomes a binary format.
_ext-table-gen_ supports the following types of columns:

* String types:
** `char`
* Integral number types:
** `smallint`
** `integer`
** `bigint`
** `int128`
* Exact numeric types (fixed point):
** `numeric`
** `decimal`
* Datetime types:
** `date`
** `time` (without time zone)
** `timestamp` (without time zone)

[#about-version]
== About this version

Firebird External Table Generator version 2.0 is the second release of this application.

This version introduces two major new features:

* Support for additional data types:
** Integral number types:
*** `smallint`
*** `integer`
*** `bigint`
*** `int128`
** Exact numeric types (fixed point):
*** `numeric`
*** `decimal`
** Datetime types:
*** `date`
*** `time` (without time zone)
*** `timestamp` (without time zone)
* Customizing the CSV parser configuration

This application is licensed under the https://www.apache.org/licenses/LICENSE-2.0[Apache 2.0 license^].

Consult the xref:ext-table-gen-user-manual.adoc[User Manual] for installation, usage examples and reference documentation.

For more information, or to report issues or submit pull requests, go to https://github.com/mrotteveel/ext-table-gen[^]

[#version-history]
=== Version history

==== _ext-table-gen_ 2.0

The following changes were made in _ext-table-gen_ 2.0

* Add support for integer types (`SMALLINT`, `INTEGER`, `BIGINT`, `INT128`) (https://github.com/mrotteveel/ext-table-gen/issues/11[#11^])
* Support custom conversions (https://github.com/mrotteveel/ext-table-gen/issues/17[#17^])
* Add `DATE` support (https://github.com/mrotteveel/ext-table-gen/issues/8[#8^])
* Add `TIME` and `TIMESTAMP` (without time zone) support (https://github.com/mrotteveel/ext-table-gen/issues/9[#9^])
* Add support for `NUMERIC`/`DECIMAL` types (https://github.com/mrotteveel/ext-table-gen/issues/12[#12^])
* Support custom CSV formats (https://github.com/mrotteveel/ext-table-gen/issues/18[#18^])
* Define `module-info.java` (https://github.com/mrotteveel/ext-table-gen/issues/16[#16^])
* The XML schema is now versioned. (https://github.com/mrotteveel/ext-table-gen/issues/14[#14^]) +
Where possible, backwards compatible changes are performed while retaining the same namespace.
See https://github.com/mrotteveel/ext-table-gen/blob/main/devdoc/adr/2023-05-xml-schema-versioning.adoc[2023-05 XML Schema Versioning^] for details.
** We introduced a minor breaking change to XSD, while not changing the namespace.
This will result in validation errors when a config file from version 1.0 is validated against the XSD of version 2.0.
We considered this change too minor to go through the trouble of changing the namespace.
+
To address this breaking change, let _ext-table-gen_ upgrade the file for you (this example uses the Windows Command Prompt continuation character `^`):
+
[listing]
----
ext-table-gen --config-in=path-to-config.xml ^
  --config-out=path-to-config.xml ^
  --overwrite-config
----
+
Alternatively, edit the XML to add the attribute `schemaVersion` with value `1.0` (i.e. `schemaVersion="1.0"`) to the `extTableGenConfig` element.
For example:
+
.XML from version 1.0
[source,xml]
----
<extTableGenConfig xmlns="https://www.lawinegevaar.nl/xsd/ext-table-gen-1.0.xsd">
    <!-- ... -->
</extTableGenConfig>
----
+
.Modified XML
[source,xml]
----
<extTableGenConfig xmlns="https://www.lawinegevaar.nl/xsd/ext-table-gen-1.0.xsd" schemaVersion="1.0">
    <!-- ... -->
</extTableGenConfig>
----

==== _ext-table-gen_ 1.0

Initial release

