= 2023-01: Project Architecture Documentation

// SPDX-FileCopyrightText: 2023 Mark Rotteveel
// SPDX-License-Identifier: Apache-2.0

== Status

* Published
* Updated: 2023-06-23

== Type

* Project-Specification
* Living document

== Context

This project is expected to be a long-running project, and it runs the risk that design decisions are either implicit or hidden in commits, tracker tickets, code comments, discussions on -- for example -- a mailinglist, or -- even worse -- just in the mind of the implementer (and likely long since forgotten).

This can be problematic because those decisions are not easy to find, reconstruct, or remember.
This can result in the following problems:

* Unintentional breaking changes
* Intentional breaking changes without proper rationale or considering the impact
* Paralysis (fear of touching things, not knowing why they are like they are)
* Doubt/second-guessing when revisiting something years later

== Decision

Changes should be documented in an _Architecture Decision Record_ (or _ADR_ for short).
This is similar to Java's JEP or Python's PEP, and blatantly copied from Jaybird Design Proposal (https://github.com/FirebirdSQL/jaybird/blob/master/devdoc/jdp/jdp-2019-01-jaybird-design-proposal.md[jdp-2019-01^]).

This includes, but is not limited to:

* Architectural changes
* Breaking changes
* New features

Ideally, changes should start with writing an ADR, that can then be discussed before implementation starts.
During implementation, the ADR can be improved and revised.

Minor changes do not need to be documented in an ADR.

=== Document structure

The ADR is identified by a number that consists of a 4 digit year, followed by two digits within that year: `yyyy-nn`.
If we ever produce more than 99 ADRs within a year (unlikely), this will be increased to three digits *for that year only*.

The document title should consist of the ADR number followed by a descriptive name:

    yyyy-nn: <descriptive title>

For example

    2023-01: Project Architecture Documentation

The document should be in AsciiDoc format, and stored in `devdoc/adr` with a filename consisting of the ADR number, followed by the lowercase, dash-separated descriptive title:

    yyyy-nn-descriptive-title.adoc

For example

    2023-01-project-architecture-documentation.adoc

An ADR should consist of the following sections.
The sections _Status_ and _Type_ are required.
The other sections should be considered the preferred structure.
Feel free to use a different structure if it makes more sense for a document.

==== Status

The status of the document.
Possible values:

* Draft
* Published: (date) -- the date is optional for living documents
* Updated by: (adr-reference)
* Replaced by: (adr-reference)
* Implemented in: (first version that implements this)
* Proposed for: (proposed version to implement this)
* Deferred indefinitely -- not implemented nor proposed for a version;
likely the feature described will never be implemented
* Updated: (date) -- the last date a previously published document was updated
+
This should be used when updating living documents.
For other types, it should be used only for textual corrections (i.e. typo fixes), or for (minor) changes which do not affect anything for application versions released after the original publish date.
Other changes to documents which are not living documents should be performed with a new ADR, and not modify the original ADR except for updating things like `Updated by` and `Replaced by`.

The status section should also reference the ADR(s) it updates or replaces:

* Updates: (adr-reference)
* Replaces: (adr-reference)

A document can have multiple status values, but _Draft_ and _Published_ are mutually exclusive.

==== Type

The type of document.
Possible values:

* Project-Specification -- Specification for the project itself (e.g. governance, way of working, etc.)
* Living document -- indicates the document can undergo fundamental changes without being replaced.
* Feature-Specification -- Specification of features, architecture and other code related things
* Experimental -- Feature is experimental and might be modified or dropped in point releases (only for use with _Feature-Specification_)
* ... (we'll likely find new types to add once we're using this)

A document can have multiple types.
The types _Project-Specification_ and _Feature-Specification_ are mutually exclusive.
The type _Experimental_ can only occur with _Feature-Specification_.
Modifications to _Experimental_ ADRs must be published as separate ADRs.

The _Living document_ type should generally only be used for _Project-Specification_ documents like this document, and not for features.

==== Context

Describes the background and context of the ADR.
For example, the reasons for proposing the changes, or 'external forces' that are relevant to the decision.

==== Decision

Documents the decision itself in sufficient detail.
For features, it should describe a rough outline of the API (the more detail, the better), and describe technical considerations for the implementation.

Preferably, the reasons for the decisions should be documented, and -- where possible -- discarded choices or alternatives should be documented.

If any follow-up features or possible future improvement were uncovered, these should be listed as well.

==== Consequences

Documents consequences of the decision.
This includes identifying expected breaking changes caused by the decision.

== Consequences

Architecture Decision Records will help make the design decisions for the project explicit.
This can be used as a guide for developers, and serve as a form of documentation for users.
