= 2023-07: Configuring Value Parsing

// SPDX-FileCopyrightText: 2023 Mark Rotteveel
// SPDX-License-Identifier: Apache-2.0

== Status

* Published: 2023-07-14
* Updated: 2023-07-15
* Implemented in: 2.0

== Type

* Feature-Specification

== Context

CSV is a string based format, and non-`char` data types need a pattern to convert from the string format to the desired data type value.
For the integral types we can use the common format of -- in regex -- `[+-]?\d+`, but other data types can have a wide variety of formats, consider dates, or decimal values with either a comma or dot as decimal separator, and others.

While we can use a sensible format as the default, for example ISO 8601 calendar date format -- `yyyy-MM-dd` -- for `date`, this would limit the usefulness to read real-world data (especially if you don't control the producer of the CSV).

In short, we need a way to convert string input to a destination data type.

In the future we may also need to perform the reverse operation: conversion from the column data type to a string value.

== Decision

Columns receive a common way to define a conversion, or converter, to convert a string to the eventual data type of the column.
If the converter is absent, a default conversion for the specific data type is applied.

A converter consists of one step to convert from a string to a (Java) data type.
The output data type of this step needs to be compatible with the Java data type of the column data type.
In the future we may introduce support for chaining multiple steps together.

For this design we're ignoring future plans to perform a reverse conversion (from external table to CSV).
We guess and assume this design will also work for that case, for example, by using the converter in reverse direction, but we'll only evaluate that when the time comes to design for that case.

The XML configuration is extended as follows:

* Data types (abstract `DatatypeType`) receives an optional element `converter`
* `converter` has one required element which specifies the converter
* As a starting point, this ADR defines the following converter.
The default conversion for the integral number data types is equivalent to using this with radix 10.
** `parseIntegralNumber` -- which will restrict values based on the enclosing type. It has one attribute:
*** `radix` (optional, defaults to `10`) -- with value in range [2, 36]

Other ADRs will define further converters to add, for example ADR 2023-08 will add the `parseDatetime` converter.

Given the design of the XML, it is possible to specify incompatible converters.
For example, using `parseIntegralNumber` for a `char` column:

[source,xml]
----
<column name="ID">
    <char>
        <converter>
            <parseIntegralNumber radix="16"/>
        </converter>
    </char>
</column>
----

If the XML defines an incompatible converter, it is rejected with an error when the XML is transformed to the _ext-table-gen_ `FbDatatype`, and exits the application.

=== Rejected Design Decisions

* Put the converter in the column instead of the data type.
+
Initially, we implemented this design, with the reasoning that it bridges between the CSV column and the Firebird column, and as such, putting it in the column felt appropriate.
+
However, during implementation, putting the converter inside the data type turned out to result in simpler code and avoided some problems with generics.
We think that making the converter an aspect of the data type in the XML config as well reduces the cognitive overhead by avoiding two diverging models.
From a design perspective, we can also argue that the data type _is_ the bridge between CSV column and Firebird column, and so putting the converter inside the data type also make sense.
* Allow multiple steps in `converter`.
+
For example, consider a conversion from string to long, and then from long (epoch milliseconds) to a datetime value, or using converters to change formatting (e.g. from string to date, back to string with a different format).
+
While this may be useful to add in the future, all current known cases require a single step, so we'll design for that, but keep the option open to extend this to allow multiple steps in the future.
* Allow reading of incompatible converters, failing on actual conversion from CSV to external table.
+
In our opinion, this results in unnecessary complexity, and fail-fast should be preferred.
* Allow reading of incompatible converters, by converting the converter result back to string and then using the default converter.
+
Though this might work for integral types, it is unlikely to work for other data types.
Being explicit about such configuration errors is preferred over trying to make it work.
See also previous item.
* Restrict compatible converters by data type through the XSD.
+
This probably leads to a more complex XSD, and our XML/XSD-fu is also not that great.
We decided to settle on validation when the internal _ext-table-gen_ model is derived from the XML.
+
This may be revisited in the future.

== Consequences

The documentation must be updated to explain how to use the converter, and to describe the configuration changes.

The XSD will be amended with the new elements, and suitable error handling will be added to reject incompatible converters.

=== Implementation consequences

Most of the consequences listed below should be considered implementation details and guideline for implementation, which may change during actual implementation or by future refactoring.

An interface `Converter<T>` is added, which provides a method `T convert(String)` to provide the actual conversion, and methods `Class<T> targetType()` to support runtime type checking.

`FbDatatype` will have a property for the `Converter`, when no converter is provided, the default conversion for the data type will be used (which may or may not be implemented using a `Converter`).

In an earlier iteration, the converter was part of the `Column`, and would be applied before calling `writeValue`, and the first parameter of `writeValue` was parameterized with `T` instead of `String`.
In a second iteration, the converter was passed from the column to the data type on each invocation of `writeValue`
During a third iteration, it turned out that moving the converter into the data type and calling it in the `writeValue` method reduced issues with generic typing, and simplified handling of default behaviour.

`FbDataType` will also receive a method `Class<T> targetType()` to specify its Java data type.
A data type will have a _default_ conversion, which will be used when no converter has been configured.
This conversion will not be exposed, and how it is performed is an implementation detail.
Existing conversion from string will be moved to that default conversion.

For the integral types `smallint`, `integer`, `bigint`, it may make sense if the converter has an additional option to support conversion using a primitive type, to avoid additional overhead of object allocation.
This will be decided during implementation.
