= 2024-01: Supporting Binary Floating Point Types

// SPDX-FileCopyrightText: 2024 Mark Rotteveel
// SPDX-License-Identifier: Apache-2.0

== Status

* Draft
* Proposed for: 3.0
* Depends on: 2023-06, 2023-07

== Type

* Feature-Specification

== Context

Firebird has two binary floating point types:

`FLOAT`:: A 32-bit IEEE-754 single precision binary floating point (a.k.a. `binary32`) +
In Firebird, it also has the alias `REAL`.
`DOUBLE PRECISION`:: A 64-bit IEEE-754 double precision binary floating point (a.k.a. `binary64`)

In Jaybird (`DefaultDataTypeCoder`), the encoding of `FLOAT` is currently implemented as:

[source,java]
----
@Override
public byte[] encodeFloat(float val) {
    return encodeInt(Float.floatToIntBits(val));
}
----

The encoding of `DOUBLE PRECISION` is currently implemented as:

[source,java]
----
@Override
public byte[] encodeDouble(double val) {
    return encodeLong(Double.doubleToLongBits(val));
}
----

The fact Jaybird converts to 32-bit or 64-bit integer values before encoding does not mean that _ext-table-gen_ needs to do the same, if an API is available that directly provides an equivalent encoding of the `float` or `double` value, we can use that as well.

The following alignment is used:

[horizontal]
`FLOAT`:: 4 bytes
`DOUBLE PRECISION`:: 8 bytes

The storage is endian-sensitive, depending on the platform of the target Firebird server;
see also https://github.com/mrotteveel/ext-table-gen/blob/main/devdoc/adr/2023-06-supporting-basic-integer-types.adoc[ADR 2023-06^].

Formats of numbers are (or can be) locale-sensitive, especially for things like decimal separator and grouping symbols.

Java provides the `java.text.NumberFormat` class (or more specifically, `java.text.DecimalFormat`) for parsing numbers in a locale-sensitive manner.
A locale-specific instance can be obtained with `NumberFormat.getInstance(Locale)`.

A standard for locale language tags is https://www.ietf.org/rfc/bcp/bcp47.txt[BCP 47^].
Java supports this through `Locale.forLanguageTag(String)` and `Locale.toLanguageTag()`.

== Decision

_ext-table-gen_ will support the `FLOAT` and `DOUBLE PRECISION` data types.

These types will only be available by editing the configuration file, they will not be derived automatically by parsing the CSV.

In the XML config, the data types will be represented by elements `float` and `doublePrecision`, without any attributes.

In Java code, the types will be represented by `FbFloat` and `FbDoublePrecision`.

The default conversion applied will use https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/Float.html#valueOf(java.lang.String)[`Float.valueOf(String)`^] or https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/Double.html#valueOf(java.lang.String)[`Double.valueOf(String)`^], meaning the format is not locale-sensitive.
Other parsing or conversion options can be configured using the `converter` element of the datatype, following the ADR 2023-07 design.

Configuration of parsing is available via the converter element `parseFloatingPointNumber` (similar to `parseIntegralNumber` and `parseBigDecimal`).
This element has the following attribute:

* `locale` (required) -- locale for locale-sensitive parsing.
The BCP 47 language tag of the desired locale.
+
Similar to `parseBigDecimal` in ADR 2023-10, we decided to make the locale required to avoid ambiguity when running the same configuration on different machines.
The locale is not relevant for a lot of datetime patterns, but is relevant for parsing numbers.

At this time, we have decided not to provide a way to specify a pattern, and instead we'll use the default patterns provided by Java.
This decision may be revisited at a later time.

The `parseFloatingPointNumber` converter in its current incarnation cannot parse numbers in scientific notation (this would require explicit configuration with a pattern, which we don't support), while the _default_ converter does.

Empty or blank values from the CSV will be interpreted as value `0`.
Other values not matching the rules of `Float.parseFloat(String)`/`Double.parseDouble(String)` or the locale-specific `NumberFormat` will produce an error.
Validation of format and range will only happen while writing the external table.

== Consequences

The documentation must be updated to explain how to use this new data types, and to describe the configuration changes.

See also previous section for some implementation consequences.
