= 2026-01: Supporting Decfloat types

// SPDX-FileCopyrightText: 2025-2026 Mark Rotteveel
// SPDX-License-Identifier: Apache-2.0

== Status

* Published: 2026-05-12
* Implemented in: 3.0

== Type

* Feature-Specification

== Context

Firebird 4.0 introduced the SQL standard `DECFLOAT[(__p__)]` with _p_ is `16` or `34`.
A `DECFLOAT` is a decimal floating point type, with either 16 base-10 digits (`DECFLOAT(16)`) or 34 base-10 digits (`DECFLOAT`/`DECFLOAT(34)`).
They are backed by an IEEE 754 `decimal64` or `decimal128`.

Beyond the SQL standard defined behaviour, Firebird's `DECFLOAT` also accepts {plus}/-Infinity, {plus}/-Nan and {plus}/-sNaN (signalling NaN).
Whether these values are accepted might depend on configuration.

When rounding (e.g. when casting a `DECFLOAT(34)` to a `DECFLOAT(16)`, or during calculations), Firebird applies a session-specific rounding, configured through `isc_dpb_decfloat_round` or `SET DECFLOAT ROUND`, defaulting to "`half up`" rounding.

Overflow (value too large) or underflow (value too small) and other error behaviour is configured through `isc_dpb_decfloat_traps` or `SET DECFLOAT TRAPS`, defaulting to raise an error on overflow, but yield `0` on underflow.

In external tables, the `DECFLOAT` types have an alignment of 8 bytes.

The https://www.rfc-editor.org/rfc/rfc4180[RFC 4180 format^] does not specify specific handling for or formats of numbers.

Formats of numbers are (or can be) locale-sensitive, especially for things like decimal separator and grouping symbols.

Java provides the `java.text.NumberFormat` class (or more specifically, `java.text.DecimalFormat`) for parsing numbers in a locale-sensitive manner.
A locale-specific instance can be obtained with `NumberFormat.getInstance(Locale)`.

A standard for locale language tags is https://www.ietf.org/rfc/bcp/bcp47.txt[BCP 47^].
Java supports this through `Locale.forLanguageTag(String)` and `Locale.toLanguageTag()`.

For full range support of `DECFLOAT`, parsing scientific notation is required.

Out of the box, Java does not provide support for the `decimal64` and `decimal128` formats.
When `DECFLOAT` support was added to Jaybird, I developed https://github.com/FirebirdSQL/decimal-java[`org.firebirdsql:decimal-java`^].
This library provides conversion between `java.math.BigDecimal` and a `Decimal64`/`Decimal128` object, with additional support for Infinities and (signalling) NaNs, and between that `DecimalNN` object and the IEEE-754 byte representation.

During conversion from `BigDecimal` (or String) to `DecimalNN`, overflow can either round to {plus}/-Infinity or throw an exception.
Underflow is always handled by rounding to `0` with a clamped (minimum) exponent.

== Decision

_ext-table-gen_ will support the `DECFLAT` datatype with both precisions (16 and 34).

This type will only be available by editing the configuration file, it will not be derived automatically by parsing the CSV.

In the XML config, the datatype will be represented by element `decfloat`, with attributes:

* `precision` (required) -- allowed value is `16` or `34`.
* `onOverflow` (optional) -- allowed values are `ROUND_TO_INFINITY` (default) or `THROW_EXCEPTION`.
+
This determines if numbers that overflow (i.e. require a too big exponent) will throw an exception or result in infinity.

In Java code, the type will be represented by `FbDecfloat16` and `FbDecfloat34`.

The default conversion applied will use https://firebirdsql.github.io/decimal-java/javadoc/org.firebirdsql.decimal/org/firebirdsql/decimal/Decimal64.html#valueOf(java.lang.String,org.firebirdsql.decimal.OverflowHandling)[`Decimal64.valueOf(String, OverflowHandling)`^] and https://firebirdsql.github.io/decimal-java/javadoc/org.firebirdsql.decimal/org/firebirdsql/decimal/Decimal128.html#valueOf(java.lang.String,org.firebirdsql.decimal.OverflowHandling)[`Decimal128.valueOf(String, OverflowHandling)`^] of https://github.com/FirebirdSQL/decimal-java[`org.firebirdsql:decimal-java`^].

Indirectly, these `valueOf` methods uses the constructor https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/math/BigDecimal.html#%3Cinit%3E(java.lang.String)[`BigDecimal(String)`^], meaning the format is not locale-sensitive.
Other parsing or conversion options can be configured using the `converter` element of the datatype, following the https://github.com/mrotteveel/ext-table-gen/blob/main/devdoc/adr/2023-07-configuring-value-parsing.adoc[ADR 2023-07] design.

We'll support use of the `parseBigDecimal` converter defined in https://github.com/mrotteveel/ext-table-gen/blob/main/devdoc/adr/2023-10-supporting-numeric-and-decimal-types.adoc[ADR 2023-10].
This converter does not handle special values ({plus}/-Infinity,{plus}/-Nan and {plus}/-sNaN).

The `parseBigDecimal` converter in its current incarnation cannot parse numbers in scientific notation (this would require explicit configuration with a pattern, which we don't support), while the _default_ converter does.

Empty or blank values from the CSV will be interpreted as value `0`.
Other values not matching the rules of `BigDecimal(String)`, the specials (in case of the _default_ converter), or the locale-specific `NumberFormat` will produce an error.
Validation of format and range will only happen while writing the external table.

== Consequences

The documentation must be updated to explain how to use this new datatype, and to describe the configuration changes.

See also previous section for some implementation consequences.
