= ext-table-gen build documentation

// SPDX-FileCopyrightText: 2023-2024 Mark Rotteveel
// SPDX-License-Identifier: Apache-2.0

[NOTE]
====
This document doesn't cover all aspects of the build.
If you miss something, please contribute using a pull request, or create an issue asking for the information.
====

== Running the build

To produce the _ext-table-gen_ application, use

[listing]
----
> ./gradlew assemble
----

To run all tests (including integration tests), use:

[listing]
----
> ./gradlew check
----

=== Integration test configuration

The integration tests require some additional configuration.
First of all, it needs a (preferably localhost) Firebird server.

Create a file called `integration-test-local.properties` in the root of the project (i.e. containing `gradlew`) with content like:

[listing]
----
test.db.host=localhost
test.db.port=13055
test.db.user=sysdba
test.db.password=masterkey
test.db.path.prefix=
test.db.path.local=./.test-db
test.db.ext-table-dir.prefix=
test.db.ext-table-dir.local=./.test-db
----

This configuration is also in `integration-test-local-example.properties`, and matches the configuration in `podman-compose.yml`.

.Settings
`test.db.host`::
Firebird hostname
`test.db.port`::
Firebird port
`test.db.user`::
Firebird user, must have the `CREATE DATABASE` privilege.
`test.db.path.prefix`::
Server-side path of the database directory.
+
Can be left empty if `DatabaseAccess` is `Restrict /some/path`.
`test.db.path.local`::
Local path corresponding to `test.db.path.prefix`.
+
This can for example be a local directory mapped as a volume into a Docker/Podman container, or a network share.
+
If not specified, it will default to `test.db.path.prefix`, but if that's empty, it uses the current directory.
`test.db.ext-table-dir.prefix`::
Server-side path of the external table directory.
+
Can be left empty if `ExternalFileAccess` is `Restrict /some/path`.
`test.db.ext-table-dir.local`::
Local path corresponding to `test.db.ext-table-dir.prefix`.
+
This can for example be a local directory mapped as a volume into a Docker/Podman container, or a network share.
+
If not specified, it will default to `test.db.ext-table-dir.prefix`, but if that's empty, it uses the current directory.

A remote Firebird server or container will work, but due to the configuration of _ext-table-gen_ and the tests, the server-side directories for `test.db.path.prefix` and `test.db.ext-table-dir.prefix` must have a locally mapped directory (network share, Docker volume, etc.) available and specified in `test.db.path.local`/`test.db.ext-table-dir.local`.

== Commit hooks

This project comes with a commit hook configuration in `.pre-commit-config.yaml`.

To use it, install `pre-commit`:

[listing]
----
pip install pre-commit
----

See https://pre-commit.com/[^] for more details.

Then -- from the repository root -- install the pre-commit hook:

[listing]
----
pre-commit install
pre-commit autoupdate
----
