= ext-table-gen build documentation

// SPDX-FileCopyrightText: 2023-2024 Mark Rotteveel
// SPDX-License-Identifier: Apache-2.0

[NOTE]
====
This document doesn't cover all aspects of the build.
If you miss something, please contribute using a pull request, or create an issue asking for the information.
====

== Running the build

To produce the _ext-table-gen_ application, use

[listing]
----
> ./gradlew assemble
----

To run all tests (including integration tests), use:

[listing]
----
> ./gradlew check
----

=== Integration test configuration

The integration tests use testcontainers-java, which may require some additional configuration when using Podman instead of Docker.

Specifically, it may be necessary to configure the podman socket.

[listing]
----
export DOCKER_HOST=unix://${XDG_RUNTIME_DIR}/podman/podman.sock
----

Or its equivalent.
For example, when configuring environment variables in the IntelliJ run settings, you'll need to put in the resolved value as it will not expand `++${XDG_RUNTIME_DIR}++` (on my system the expansion is `/run/user/1000`).

Alternatively, in your home directory, create a `.testcontainers.properties` with:

[listing]
----
docker.host=unix\:///run/user/1000/podman/podman.sock
----

(Replace that `/run/user/1000` as appropriate.)

Some sources (like https://www.baeldung.com/java-podman-configure-testcontainers[this article^]) suggest you may also need to disable Ryuk:

[listing]
----
export TESTCONTAINERS_RYUK_DISABLED=true
----

== Commit hooks

This project comes with a commit hook configuration in `.pre-commit-config.yaml`.

To use it, install `pre-commit`:

[listing]
----
pip install pre-commit
----

See https://pre-commit.com/[^] for more details.

Then -- from the repository root -- install the pre-commit hook:

[listing]
----
pre-commit install
pre-commit autoupdate
----
